/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package randomprogram;

import java.awt.CardLayout;
import java.math.BigDecimal;
import java.security.SecureRandom;
import java.math.BigInteger;
/**
 *
 * @author ADMIN
 */
public class RandomSoThapPhanGUI extends javax.swing.JPanel {

    /**
     * Creates new form RandomSoThapPhanGUI
     */
    public RandomSoThapPhanGUI() {
        initComponents();
        this.regex_double = "[+-]?((\\d+(\\.\\d*)?)|(\\.\\d+))([Ee][+-]?\\d+)?";
        this.regex_integer = "[+-]?\\d+";
        this.sinhSoThapPhan = new RandomSoThapPhan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TroVeHome = new javax.swing.JButton();
        TieuDe = new javax.swing.JLabel();
        TieuDeKhoangCachMin = new javax.swing.JLabel();
        TIeuDeKhoangCachMax = new javax.swing.JLabel();
        SoLuongChuSoLamTron = new javax.swing.JTextField();
        KhoangCachMin = new javax.swing.JTextField();
        TieuDeSoLuongChuSoLamTron = new javax.swing.JLabel();
        KhoangCachMax = new javax.swing.JTextField();
        LamMoi = new javax.swing.JButton();
        SinhSo = new javax.swing.JButton();
        TieuDeKetQua = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        KetQua = new javax.swing.JTextArea();
        CanhBaoLoi1 = new javax.swing.JLabel();
        CanhBaoLoi2 = new javax.swing.JLabel();
        CanhBaoLoi3 = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        TroVeHome.setText("Quay về trang chủ");
        TroVeHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TroVeHomeActionPerformed(evt);
            }
        });

        TieuDe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TieuDe.setText("         Sinh số thập phân");

        TieuDeKhoangCachMin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TieuDeKhoangCachMin.setText("Nhập khoảng cách min:");

        TIeuDeKhoangCachMax.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TIeuDeKhoangCachMax.setText("Nhập khoảng cách max:");

        SoLuongChuSoLamTron.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SoLuongChuSoLamTron.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SoLuongChuSoLamTronFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SoLuongChuSoLamTronFocusLost(evt);
            }
        });

        KhoangCachMin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KhoangCachMin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                KhoangCachMinFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                KhoangCachMinFocusLost(evt);
            }
        });

        TieuDeSoLuongChuSoLamTron.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TieuDeSoLuongChuSoLamTron.setText("Nhập số lượng chữ số làm tròn:");

        KhoangCachMax.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KhoangCachMax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                KhoangCachMaxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                KhoangCachMaxFocusLost(evt);
            }
        });

        LamMoi.setText("Làm Mới");
        LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LamMoiActionPerformed(evt);
            }
        });

        SinhSo.setText("Sinh Số");
        SinhSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SinhSoActionPerformed(evt);
            }
        });

        TieuDeKetQua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TieuDeKetQua.setText("Kết quả:");

        KetQua.setColumns(20);
        KetQua.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        KetQua.setRows(5);
        jScrollPane2.setViewportView(KetQua);
        KetQua.setEditable(false);

        CanhBaoLoi1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CanhBaoLoi1.setForeground(new java.awt.Color(255, 0, 0));

        CanhBaoLoi2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CanhBaoLoi2.setForeground(new java.awt.Color(255, 0, 0));

        CanhBaoLoi3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CanhBaoLoi3.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142)
                .addComponent(SinhSo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TroVeHome)
                        .addGap(100, 100, 100)
                        .addComponent(TieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TieuDeSoLuongChuSoLamTron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TIeuDeKhoangCachMax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TieuDeKhoangCachMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(TieuDeKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CanhBaoLoi3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(SoLuongChuSoLamTron)
                            .addComponent(KhoangCachMin)
                            .addComponent(KhoangCachMax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addComponent(CanhBaoLoi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CanhBaoLoi2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TroVeHome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TieuDeKhoangCachMin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KhoangCachMin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CanhBaoLoi1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TIeuDeKhoangCachMax, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KhoangCachMax, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CanhBaoLoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TieuDeSoLuongChuSoLamTron, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SoLuongChuSoLamTron, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CanhBaoLoi3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SinhSo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TieuDeKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TroVeHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TroVeHomeActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) ManageGUI.cards.getLayout();
        layout.show(ManageGUI.cards, "HomePageGUI");
    }//GEN-LAST:event_TroVeHomeActionPerformed

    private void SoLuongChuSoLamTronFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SoLuongChuSoLamTronFocusGained
        // TODO add your handling code here:
        CanhBaoLoi3.setText("");
    }//GEN-LAST:event_SoLuongChuSoLamTronFocusGained

    private void SoLuongChuSoLamTronFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SoLuongChuSoLamTronFocusLost
        // TODO add your handling code here:
        String chuoi = SoLuongChuSoLamTron.getText();
        if (!chuoi.isEmpty()) {
            if (!chuoi.matches(regex_integer)) {
                CanhBaoLoi3.setText("Không phải là số nguyên.");
                KetQua.setText("");
            } else {
                CanhBaoLoi3.setText("");
            }
        } else {
            CanhBaoLoi3.setText("");
        }
    }//GEN-LAST:event_SoLuongChuSoLamTronFocusLost

    private void KhoangCachMinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KhoangCachMinFocusGained
        // TODO add your handling code here:
        CanhBaoLoi1.setText("");
    }//GEN-LAST:event_KhoangCachMinFocusGained

    private void KhoangCachMinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KhoangCachMinFocusLost
        // TODO add your handling code here:
        String chuoi = KhoangCachMin.getText();
        if (!chuoi.isEmpty()) {
            if (!chuoi.matches(regex_double)) {
                CanhBaoLoi1.setText("Không phải là số thập phân.");
                KetQua.setText("");
            } else {
                CanhBaoLoi1.setText("");
            }
        } else {
            CanhBaoLoi1.setText("");
        }
    }//GEN-LAST:event_KhoangCachMinFocusLost

    private void KhoangCachMaxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KhoangCachMaxFocusGained
        // TODO add your handling code here:
        CanhBaoLoi2.setText("");
    }//GEN-LAST:event_KhoangCachMaxFocusGained

    private void KhoangCachMaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KhoangCachMaxFocusLost
        // TODO add your handling code here:
        String chuoi = KhoangCachMax.getText();
        if (!chuoi.isEmpty()) {
            if (!chuoi.matches(regex_double)) {
                CanhBaoLoi2.setText("Không phải là số thập phân.");
                KetQua.setText("");
            } else {
                CanhBaoLoi2.setText("");
            }
        } else {
            CanhBaoLoi2.setText("");
        }
    }//GEN-LAST:event_KhoangCachMaxFocusLost

    private void LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LamMoiActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_LamMoiActionPerformed

    private void SinhSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SinhSoActionPerformed
        // TODO add your handling code here:
        String chuoi1 = KhoangCachMin.getText();
        String chuoi2 = KhoangCachMax.getText();
        String chuoi3 = SoLuongChuSoLamTron.getText();
        boolean kiemTraCuPhap = true;
        if (!chuoi1.isEmpty()) {
            if (!chuoi1.matches(regex_double)) {
                CanhBaoLoi1.setText("Không phải là số thập phân.");
                kiemTraCuPhap = false;
            } else {
                CanhBaoLoi1.setText("");
            }
        } else {
            CanhBaoLoi1.setText("Bạn chưa nhập gì cả.");
            kiemTraCuPhap = false;
        }
        if (!chuoi2.isEmpty()) {
            if (!chuoi2.matches(regex_double)) {
                CanhBaoLoi2.setText("Không phải là số thập phân.");
                kiemTraCuPhap = false;
            } else {
                CanhBaoLoi2.setText("");
            }
        } else {
            CanhBaoLoi2.setText("Bạn chưa nhập gì cả.");
            kiemTraCuPhap = false;
        }
        if (!chuoi3.isEmpty()) {
            if (!chuoi3.matches(regex_integer)) {
                CanhBaoLoi3.setText("Không phải là số nguyên.");
                kiemTraCuPhap = false;
            } else {
                CanhBaoLoi3.setText("");
            }
        } else {
            CanhBaoLoi3.setText("");
            chuoi3 = "18";
        }
        if (kiemTraCuPhap)
        {
            try
            {
                BigDecimal soDau = new BigDecimal(chuoi1);
                BigDecimal soCuoi = new BigDecimal(chuoi2);
                BigInteger soLuongChuSo = new BigInteger(chuoi3);
                KetQua.setText(sinhSoThapPhan.sinh(soDau, soCuoi, soLuongChuSo).toString());                
            } catch (Exception loi)
            {
                KetQua.setText(loi.getMessage());
            }
        } else
        {
            KetQua.setText("");
        }
    }//GEN-LAST:event_SinhSoActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        requestFocusInWindow();
    }//GEN-LAST:event_formMouseClicked

    public void clear() {
        KhoangCachMin.setText("");
        KhoangCachMax.setText("");
        SoLuongChuSoLamTron.setText("");
        KetQua.setText("");
        CanhBaoLoi1.setText("");
        CanhBaoLoi2.setText("");
        CanhBaoLoi3.setText("");
    }

    private RandomSoThapPhan sinhSoThapPhan;
    private String regex_double;
    private String regex_integer;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CanhBaoLoi1;
    private javax.swing.JLabel CanhBaoLoi2;
    private javax.swing.JLabel CanhBaoLoi3;
    private javax.swing.JTextArea KetQua;
    private javax.swing.JTextField KhoangCachMax;
    private javax.swing.JTextField KhoangCachMin;
    private javax.swing.JButton LamMoi;
    private javax.swing.JButton SinhSo;
    private javax.swing.JTextField SoLuongChuSoLamTron;
    private javax.swing.JLabel TIeuDeKhoangCachMax;
    private javax.swing.JLabel TieuDe;
    private javax.swing.JLabel TieuDeKetQua;
    private javax.swing.JLabel TieuDeKhoangCachMin;
    private javax.swing.JLabel TieuDeSoLuongChuSoLamTron;
    private javax.swing.JButton TroVeHome;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
