/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package randomprogram;

import java.awt.CardLayout;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.security.SecureRandom;

/**
 *
 * @author ADMIN
 */
public class RandomSoNguyenGUI extends javax.swing.JPanel {

    /**
     * Creates new form RandomSoNguyenGUI
     */
    public RandomSoNguyenGUI() {
        initComponents();
        this.regex_integer = "[+-]?\\d+";
        this.sinhSoNguyen = new RandomSoNguyen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TieuDe = new javax.swing.JLabel();
        TieuDeKhoangCachMin = new javax.swing.JLabel();
        TIeuDeKhoangCachMax = new javax.swing.JLabel();
        KhoangCachMax = new javax.swing.JTextField();
        TroVeHome = new javax.swing.JButton();
        LamMoi = new javax.swing.JButton();
        SinhSo = new javax.swing.JButton();
        TieuDeKetQua = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        KetQua = new javax.swing.JTextArea();
        KhoangCachMin = new javax.swing.JTextField();
        CanhBaoLoi1 = new javax.swing.JLabel();
        CanhBaoLoi2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 600));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        TieuDe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TieuDe.setText("            Sinh số nguyên");

        TieuDeKhoangCachMin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TieuDeKhoangCachMin.setText("Nhập khoảng cách min:");

        TIeuDeKhoangCachMax.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TIeuDeKhoangCachMax.setText("Nhập khoảng cách max:");

        KhoangCachMax.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KhoangCachMax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                KhoangCachMaxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                KhoangCachMaxFocusLost(evt);
            }
        });

        TroVeHome.setText("Quay về trang chủ");
        TroVeHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TroVeHomeActionPerformed(evt);
            }
        });

        LamMoi.setText("Làm Mới");
        LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LamMoiActionPerformed(evt);
            }
        });

        SinhSo.setText("Sinh Số");
        SinhSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SinhSoActionPerformed(evt);
            }
        });

        TieuDeKetQua.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TieuDeKetQua.setText("Kết quả:");

        KetQua.setColumns(20);
        KetQua.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        KetQua.setRows(5);
        jScrollPane2.setViewportView(KetQua);
        KetQua.setEditable(false);

        KhoangCachMin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KhoangCachMin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                KhoangCachMinFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                KhoangCachMinFocusLost(evt);
            }
        });

        CanhBaoLoi1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CanhBaoLoi1.setForeground(new java.awt.Color(255, 0, 0));

        CanhBaoLoi2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CanhBaoLoi2.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(TieuDeKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TIeuDeKhoangCachMax, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TieuDeKhoangCachMin, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CanhBaoLoi2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(CanhBaoLoi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(KhoangCachMax)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addComponent(KhoangCachMin))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TroVeHome)
                        .addGap(94, 94, 94)
                        .addComponent(TieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166)
                        .addComponent(SinhSo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(TieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TroVeHome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KhoangCachMin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TieuDeKhoangCachMin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(CanhBaoLoi1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KhoangCachMax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TIeuDeKhoangCachMax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CanhBaoLoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SinhSo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TieuDeKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SinhSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SinhSoActionPerformed
        // TODO add your handling code here:
        String chuoi1 = KhoangCachMin.getText();
        String chuoi2 = KhoangCachMax.getText();
        boolean kiemTraCuPhap = true;
        if (!chuoi1.isEmpty()) {
            if (!chuoi1.matches(regex_integer)) {
                CanhBaoLoi1.setText("Không phải là số nguyên.");
                kiemTraCuPhap = false;
            } else {
                CanhBaoLoi1.setText("");
            }
        } else {
            CanhBaoLoi1.setText("Bạn chưa nhập gì cả.");
            kiemTraCuPhap = false;
        }
        if (!chuoi2.isEmpty()) {
            if (!chuoi2.matches(regex_integer)) {
                CanhBaoLoi2.setText("Không phải là số nguyên.");
                kiemTraCuPhap = false;
            } else {
                CanhBaoLoi2.setText("");
            }
        } else {
            CanhBaoLoi2.setText("Bạn chưa nhập gì cả.");
            kiemTraCuPhap = false;
        }
        if (kiemTraCuPhap) {
            try
            {
                BigInteger soDau = new BigInteger(chuoi1);
                BigInteger soCuoi = new BigInteger(chuoi2);
                KetQua.setText(sinhSoNguyen.sinh(soDau, soCuoi).toString());
            } catch (Exception loi)
            {
                KetQua.setText(loi.getMessage());
            }
        } else
            KetQua.setText("");
    }//GEN-LAST:event_SinhSoActionPerformed

    private void TroVeHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TroVeHomeActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) ManageGUI.cards.getLayout();
        layout.show(ManageGUI.cards, "HomePageGUI");
    }//GEN-LAST:event_TroVeHomeActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        requestFocusInWindow();
    }//GEN-LAST:event_formMouseClicked

    private void KhoangCachMinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KhoangCachMinFocusLost
        // TODO add your handling code here:
        String chuoi = KhoangCachMin.getText();
        if (!chuoi.isEmpty()) {
            if (!chuoi.matches(regex_integer)) {
                CanhBaoLoi1.setText("Không phải là số nguyên.");
                KetQua.setText("");
            } else {
                CanhBaoLoi1.setText("");
            }
        } else {
            CanhBaoLoi1.setText("");
        }
    }//GEN-LAST:event_KhoangCachMinFocusLost

    private void KhoangCachMaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KhoangCachMaxFocusLost
        // TODO add your handling code here:
        String chuoi = KhoangCachMax.getText();
        if (!chuoi.isEmpty()) {
            if (!chuoi.matches(regex_integer)) {
                CanhBaoLoi2.setText("Không phải là số nguyên.");
                KetQua.setText("");
            } else {
                CanhBaoLoi2.setText("");
            }
        } else {
            CanhBaoLoi2.setText("");
        }
    }//GEN-LAST:event_KhoangCachMaxFocusLost

    private void LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LamMoiActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_LamMoiActionPerformed

    private void KhoangCachMinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KhoangCachMinFocusGained
        // TODO add your handling code here:
        CanhBaoLoi1.setText("");
    }//GEN-LAST:event_KhoangCachMinFocusGained

    private void KhoangCachMaxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KhoangCachMaxFocusGained
        // TODO add your handling code here:
        CanhBaoLoi2.setText("");
    }//GEN-LAST:event_KhoangCachMaxFocusGained

    public void clear() {
        KhoangCachMin.setText("");
        KhoangCachMax.setText("");
        KetQua.setText("");
        CanhBaoLoi1.setText("");
        CanhBaoLoi2.setText("");
    }

    private RandomSoNguyen sinhSoNguyen;
    private final String regex_integer;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CanhBaoLoi1;
    private javax.swing.JLabel CanhBaoLoi2;
    private javax.swing.JTextArea KetQua;
    private javax.swing.JTextField KhoangCachMax;
    private javax.swing.JTextField KhoangCachMin;
    private javax.swing.JButton LamMoi;
    private javax.swing.JButton SinhSo;
    private javax.swing.JLabel TIeuDeKhoangCachMax;
    private javax.swing.JLabel TieuDe;
    private javax.swing.JLabel TieuDeKetQua;
    private javax.swing.JLabel TieuDeKhoangCachMin;
    private javax.swing.JButton TroVeHome;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
